### ISSUE TITLE
freegpt用的模型不是gpt-3.5-turbo嘛，为什么代码里是text-davinci-002-render

### ISSUE THREAD

**Issue by Spider4U** [JettChenT/freegpt-rev#1]
![gpt](https://user-images.githubusercontent.com/39551480/224598080-16f6e025-4691-4783-a1fe-06ec1c0b37eb.png)

看图上是用的gpt-3.5-turbo的API

**Comment by JettChenT** [comment]
这个没有具体研究过，我是按照分析网站里发出的network request 为准的。

**Comment by Spider4U** [comment]
> 

测试了下代码，请求不了。。。

**Comment by JettChenT** [comment]
有可能是会的，他那个接口加了cloudflare, 可以多试试几个ip
